-- Users (Supports both authenticated users and guests)
CREATE TABLE users (
    id UUID PRIMARY KEY, -- generated by client or server
    email VARCHAR(255),
    password_hash VARCHAR(255),
    name VARCHAR(100) DEFAULT NULL,
    role VARCHAR(50) DEFAULT 'user',
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Main Categories (Mood, Hustle, Relationship, Occasion, Deep, Source)
CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT
);

-- Subcategories (Melancholy, Uplifting, etc.)
CREATE TABLE subcategories (
    id SERIAL PRIMARY KEY,
    category_id INTEGER REFERENCES categories(id),
    name VARCHAR(50) NOT NULL,
    tags TEXT[] -- Keywords for search/matching
);

-- Quotes
CREATE TABLE quotes (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    author VARCHAR(100) DEFAULT 'Unknown',
    subcategory_id INTEGER REFERENCES subcategories (id),
    background_color VARCHAR(50) DEFAULT '#e0e5ec',
    text_color VARCHAR(50) DEFAULT '#334155',
    font_family VARCHAR(50) DEFAULT 'Inter, sans-serif',
    visibility VARCHAR(20) DEFAULT 'public' CHECK (
        visibility IN (
            'public',
            'unlisted',
            'private'
        )
    ),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    user_id UUID REFERENCES users (id) ON DELETE SET NULL
);

-- User Interactions for the Smart System
CREATE TABLE user_interactions (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users (id),
    quote_id INTEGER REFERENCES quotes (id),
    interaction_type VARCHAR(20) NOT NULL, -- 'view', 'like', 'remix', 'share'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Quote comments
CREATE TABLE quote_comments (
    id SERIAL PRIMARY KEY,
    quote_id INTEGER REFERENCES quotes (id) ON DELETE CASCADE,
    user_id UUID REFERENCES users (id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Migrations for already-provisioned DBs
ALTER TABLE quotes
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE quote_comments
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Site widgets (Right sidebar content, etc.)
CREATE TABLE IF NOT EXISTS site_widgets (
    id SERIAL PRIMARY KEY,
    key VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(100),
    content JSONB NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_interactions_user ON user_interactions (user_id);

CREATE INDEX IF NOT EXISTS idx_quotes_subcategory ON quotes (subcategory_id);

CREATE INDEX IF NOT EXISTS idx_quotes_created_at ON quotes (created_at);

CREATE INDEX IF NOT EXISTS idx_quotes_user_id ON quotes (user_id);

CREATE INDEX IF NOT EXISTS idx_quote_comments_quote ON quote_comments (quote_id);

CREATE INDEX IF NOT EXISTS idx_quote_comments_created_at ON quote_comments (created_at);

CREATE INDEX IF NOT EXISTS idx_quote_comments_user_id ON quote_comments (user_id);